// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFKw3OCWXd2E2iRSdyibXg-uxWEdePQrQ',
    appId: '1:488604938387:web:433688473ce8faf1fedd66',
    messagingSenderId: '488604938387',
    projectId: 'fir-demo-a64e8',
    authDomain: 'fir-demo-a64e8.firebaseapp.com',
    databaseURL: 'https://fir-demo-a64e8-default-rtdb.firebaseio.com',
    storageBucket: 'fir-demo-a64e8.firebasestorage.app',
    measurementId: 'G-41R3HVVPGB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFUEf01pzx_gg7VuENnL5H9LSBMErbBk4',
    appId: '1:488604938387:android:fe3739403033a354fedd66',
    messagingSenderId: '488604938387',
    projectId: 'fir-demo-a64e8',
    databaseURL: 'https://fir-demo-a64e8-default-rtdb.firebaseio.com',
    storageBucket: 'fir-demo-a64e8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9rgwpQ2pkd-ViGPiW2Xd0t8aKnyak5HI',
    appId: '1:488604938387:ios:c0eeef041e68b159fedd66',
    messagingSenderId: '488604938387',
    projectId: 'fir-demo-a64e8',
    databaseURL: 'https://fir-demo-a64e8-default-rtdb.firebaseio.com',
    storageBucket: 'fir-demo-a64e8.firebasestorage.app',
    iosBundleId: 'com.example.firebasedemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB9rgwpQ2pkd-ViGPiW2Xd0t8aKnyak5HI',
    appId: '1:488604938387:ios:c0eeef041e68b159fedd66',
    messagingSenderId: '488604938387',
    projectId: 'fir-demo-a64e8',
    databaseURL: 'https://fir-demo-a64e8-default-rtdb.firebaseio.com',
    storageBucket: 'fir-demo-a64e8.firebasestorage.app',
    iosBundleId: 'com.example.firebasedemo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBFKw3OCWXd2E2iRSdyibXg-uxWEdePQrQ',
    appId: '1:488604938387:web:07b51aa76c4801fafedd66',
    messagingSenderId: '488604938387',
    projectId: 'fir-demo-a64e8',
    authDomain: 'fir-demo-a64e8.firebaseapp.com',
    databaseURL: 'https://fir-demo-a64e8-default-rtdb.firebaseio.com',
    storageBucket: 'fir-demo-a64e8.firebasestorage.app',
    measurementId: 'G-0T8EKW0F37',
  );
}
